//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Jan Joris.
        /// </summary>
        public static string AboutViewBy {
            get {
                return ResourceManager.GetString("AboutViewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string AboutViewContactButton {
            get {
                return ResourceManager.GetString("AboutViewContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Section xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///  &lt;Paragraph/&gt;&lt;Paragraph FontWeight=&quot;Light&quot;&gt;
        ///      Hi there. Welcome to Track. This app has been built with passion, a lot of cursing, crying and occasional eufory. So, when you encounter an issue, please hit the contact button instead of handing out a 1 star review.&lt;/Paragraph&gt;
        ///  &lt;Paragraph/&gt;&lt;Paragraph FontWeight=&quot;Light&quot;&gt;
        ///    Track is not finished just yet. A lot of functionality is still to be included. Expect searching connec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutViewDisclaimer {
            get {
                return ResourceManager.GetString("AboutViewDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string AboutViewHeaderChangelog {
            get {
                return ResourceManager.GetString("AboutViewHeaderChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string AboutViewHeaderInfo {
            get {
                return ResourceManager.GetString("AboutViewHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iRail.
        /// </summary>
        public static string AboutViewHeaderiRail {
            get {
                return ResourceManager.GetString("AboutViewHeaderiRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Section xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///  &lt;Paragraph FontWeight=&quot;Light&quot;&gt;
        ///  “By 2025 we will double the amount of public transit users,” says UITP (the international organisation for public transport). This is a noble goal that is great food for thought. Not only different transport networks will need to connect flawlessly, also social networks, GPS systems, calendars and publicly available data can be integrated to provide a networked mobility experience, leading to a m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutViewiRail {
            get {
                return ResourceManager.GetString("AboutViewiRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string AboutViewReviewButton {
            get {
                return ResourceManager.GetString("AboutViewReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string AboutViewUnknownAssembly {
            get {
                return ResourceManager.GetString("AboutViewUnknownAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string AboutViewVersion {
            get {
                return ResourceManager.GetString("AboutViewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the API is not accepting any requests right now, please try again later.
        /// </summary>
        public static string APIClientErrorDown {
            get {
                return ResourceManager.GetString("APIClientErrorDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string AppBarButtomSubmit {
            get {
                return ResourceManager.GetString("AppBarButtomSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • initial release.
        /// </summary>
        public static string ChangeLog100_1 {
            get {
                return ResourceManager.GetString("ChangeLog100_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string ClientLang {
            get {
                return ResourceManager.GetString("ClientLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you succesfully added {0} to favorites.
        /// </summary>
        public static string FavoriteAdded {
            get {
                return ResourceManager.GetString("FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already have {0} in your favorites.
        /// </summary>
        public static string FavoriteExists {
            get {
                return ResourceManager.GetString("FavoriteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer.
        /// </summary>
        public static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string MainViewFavorites {
            get {
                return ResourceManager.GetString("MainViewFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string MainViewNearby {
            get {
                return ResourceManager.GetString("MainViewNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string MainViewStations {
            get {
                return ResourceManager.GetString("MainViewStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we could not load station info right now, please try again later.
        /// </summary>
        public static string MessageStationInfoError {
            get {
                return ResourceManager.GetString("MessageStationInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid station name.
        /// </summary>
        public static string MessageValidStationName {
            get {
                return ResourceManager.GetString("MessageValidStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we could not load vehicle info right now, please try again later.
        /// </summary>
        public static string MessageVehicleInfoError {
            get {
                return ResourceManager.GetString("MessageVehicleInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} station.
        /// </summary>
        public static string NavigationStation {
            get {
                return ResourceManager.GetString("NavigationStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting location.
        /// </summary>
        public static string ProgressAquiringLocation {
            get {
                return ResourceManager.GetString("ProgressAquiringLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading stations.
        /// </summary>
        public static string ProgressLoadingStations {
            get {
                return ResourceManager.GetString("ProgressLoadingStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string SearchViewDate {
            get {
                return ResourceManager.GetString("SearchViewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string SearchViewFrom {
            get {
                return ResourceManager.GetString("SearchViewFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchViewHeader {
            get {
                return ResourceManager.GetString("SearchViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string SearchViewTime {
            get {
                return ResourceManager.GetString("SearchViewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string SearchViewTo {
            get {
                return ResourceManager.GetString("SearchViewTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delay.
        /// </summary>
        public static string StationOverviewDelay {
            get {
                return ResourceManager.GetString("StationOverviewDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        public static string StationOverViewPlatform {
            get {
                return ResourceManager.GetString("StationOverViewPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we know it&apos;s sad, but we really need an internet connection to proceed, sorry about that..
        /// </summary>
        public static string ToastNoInternet {
            get {
                return ResourceManager.GetString("ToastNoInternet", resourceCulture);
            }
        }
    }
}
