//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the API is not accepting any requests right now, please try again later.
        /// </summary>
        public static string APIClientErrorDown {
            get {
                return ResourceManager.GetString("APIClientErrorDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string AppBarButtomSubmit {
            get {
                return ResourceManager.GetString("AppBarButtomSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string ClientLang {
            get {
                return ResourceManager.GetString("ClientLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer.
        /// </summary>
        public static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string MainViewFavorites {
            get {
                return ResourceManager.GetString("MainViewFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string MainViewNearby {
            get {
                return ResourceManager.GetString("MainViewNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string MainViewStations {
            get {
                return ResourceManager.GetString("MainViewStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we could not load station info right now, please try again later.
        /// </summary>
        public static string MessageStationInfoError {
            get {
                return ResourceManager.GetString("MessageStationInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we could not load vehicle info right now, please try again later.
        /// </summary>
        public static string MessageVehicleInfoError {
            get {
                return ResourceManager.GetString("MessageVehicleInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} station.
        /// </summary>
        public static string NavigationStation {
            get {
                return ResourceManager.GetString("NavigationStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting location.
        /// </summary>
        public static string ProgressAquiringLocation {
            get {
                return ResourceManager.GetString("ProgressAquiringLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading stations.
        /// </summary>
        public static string ProgressLoadingStations {
            get {
                return ResourceManager.GetString("ProgressLoadingStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchViewHeader {
            get {
                return ResourceManager.GetString("SearchViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delay.
        /// </summary>
        public static string StationOverviewDelay {
            get {
                return ResourceManager.GetString("StationOverviewDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        public static string StationOverViewPlatform {
            get {
                return ResourceManager.GetString("StationOverViewPlatform", resourceCulture);
            }
        }
    }
}
